FROM php:5.6.17-apache 
RUN a2enmod rewrite expires
# install the PHP extensions we need
RUN apt-get update && apt-get install -y libpng12-dev libjpeg-dev mariadb-client-10.0 git\
    && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
    && docker-php-ext-install gd mysqli opcache mbstring \
    && mkdir -m 777 /var/log/php \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y vim postfix rsyslog && rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
    && usermod -u 1000 www-data \
    && groupmod -g 1000 www-data

COPY etc/php/php.ini /usr/local/etc/php/php.ini
COPY docker-entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

CMD ["apache2-foreground"]
